In [1]:
print("Hello World")

Hello World


In [2]:
print("Ananda")

Ananda


In [13]:
print("hi")

hi


In [4]:
10+20

30

In [5]:
10-20

-10

In [6]:
30*23

690

In [9]:
a=30
b=40
print(a+b)
print(a-b)
print(a*b)
print(a/b)

70
-10
1200
0.75


In [10]:
40/20

2.0

In [11]:
a=30
b=40
print(a+b)
print(a-b)
print(a*b)
print(a/b)

70
-10
1200
0.75


In [1]:
#code from chatgpt
# Import libraries
import numpy as np
import pandas as pd

# -------------------------
# 1. BASIC NUMPY OPERATIONS
# -------------------------

# Create NumPy arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Array a:", a)
print("Array b:", b)

# Arithmetic operations
print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)

# Other basic operations
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))

# Slicing NumPy array
print("First 3 elements:", a[:3])
print("Last 2 elements:", a[-2:])


# -------------------------
# 2. CREATE PANDAS DATAFRAME
# -------------------------

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

print("\nDataFrame:")
print(df)


# -------------------------
# 3. INSPECT DATAFRAME
# -------------------------

print("\nFirst 2 rows:")
print(df.head(2))

print("\nDataFrame information:")
print(df.info())

print("\nStatistical summary:")
print(df.describe())


# -------------------------
# 4. INDEXING
# -------------------------

# Select one column
print("\nNames:")
print(df["Name"])

# Select multiple columns
print("\nName and Marks:")
print(df[["Name", "Marks"]])

# Select row by position
print("\nFirst row:")
print(df.iloc[0])

# Select row by index
print("\nRow with index 2:")
print(df.loc[2])


# -------------------------
# 5. SLICING
# -------------------------

# First 2 rows
print("\nFirst 2 rows:")
print(df.iloc[:2])

# Rows 1 to 3
print("\nRows 1 to 3:")
print(df.iloc[1:4])

# Rows and selected columns
print("\nRows 1-3, Name and Marks:")
print(df.loc[1:3, ["Name", "Marks"]])


# -------------------------
# 6. FILTERING
# -------------------------

# Students with marks greater than 80
print("\nStudents with marks > 80:")
print(df[df["Marks"] > 80])

Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]
Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Sum: 15
Mean: 3.0
Maximum: 5
Minimum: 1
First 3 elements: [1 2 3]
Last 2 elements: [4 5]

DataFrame:
      Name  Age  Marks
0    Alice   20     85
1      Bob   21     90
2  Charlie   19     78
3    David   22     88

First 2 rows:
    Name  Age  Marks
0  Alice   20     85
1    Bob   21     90

DataFrame information:
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str  
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 248.0 bytes
None

Statistical summary:
             Age      Marks
count   4.000000   4.000000
mean   20.500000  85.250000
std     1.290994   5.251984
min    19.000000  78.000000
25%    19.750000  83.25000

In [15]:
#LAB Code
import numpy as np
import pandas as pd

# NumPy
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)
print(a * b)
print(np.mean(a))
print(a[:3])       # slicing

# Pandas DataFrame
df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22],
    "Marks": [80, 90, 85]
})

print(df)           # display
print(df.head())    # inspect
print(df["Name"])   # column indexing
print(df.iloc[0])   # row indexing
print(df.iloc[:2])  # slicing
print(df[df["Marks"] > 80])  # filtering

[11 22 33 44 55]
[ 10  40  90 160 250]
3.0
[1 2 3]
  Name  Age  Marks
0    A   20     80
1    B   21     90
2    C   22     85
  Name  Age  Marks
0    A   20     80
1    B   21     90
2    C   22     85
0    A
1    B
2    C
Name: Name, dtype: str
Name      A
Age      20
Marks    80
Name: 0, dtype: object
  Name  Age  Marks
0    A   20     80
1    B   21     90
  Name  Age  Marks
1    B   21     90
2    C   22     85


In [4]:
#LAB Code
import numpy as np
import pandas as pd
arr=np.array([10,20,30,40,50])
print("array:",arr)
print("Mean is:",arr.mean())
print("Reshaped 2D:\n",arr.reshape(5,1))
print("Sliced from index 1,2,3:",arr[1:4])
data ={
    'Name' : ['Anjali','Akshatha','Anagha','Ashiq'],
    "Marks" : [86,76,66,56],
    "Branch" : ['CSE','CSE','CSE','CSE']
}
df = pd.DataFrame(data)
print("\n First 2 Rows:\n",df.iloc[0:4])
print("\n Marks Column \n",df['Marks'])
print("\n Rows where Marks>70:\n",df[df['Marks']>70])

array: [10 20 30 40 50]
Mean is: 30.0
Reshaped 2D:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Sliced from index 1,2,3: [20 30 40]

 First 2 Rows:
        Name  Marks Branch
0    Anjali     86    CSE
1  Akshatha     76    CSE
2    Anagha     66    CSE
3     Ashiq     56    CSE

 Marks Column 
 0    86
1    76
2    66
3    56
Name: Marks, dtype: int64

 Rows where Marks>70:
        Name  Marks Branch
0    Anjali     86    CSE
1  Akshatha     76    CSE
